server:
  port: 5001

#Eureka配置
eureka:
  instance:
    hostname: smeureka5001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向eureka注册中心注册自己
    fetch-registry: false #fetch-registry如果为false，则表示自己为注册中心
    service-url:
      #监控页面~(单机)http://${eureka.instance.hostname}:${server.port}/eureka/
      #集群（关联）
      defaultZone: http://smeureka5002.com:5002/eureka/,http://smeureka5003.com:5003/eureka/