server:
  port: 8003

#mybatis配置
mybatis:
  type-aliases-package: com.feige.savememory.entity
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#spring的配置
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: savememory-providers
  datasource:
    url: jdbc:mysql://localhost:3306/savememory?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://smeureka5001.com:5001/eureka/,http://smeureka5002.com:5002/eureka/,http://smeureka5003.com:5003/eureka/
  instance:
    instance-id: savememory-provider-8003
    prefer-ip-address: true #可以显示服务ip

#info配置
info:
  app.name: LY-savememory
  company.name: blog.feigeapp.com

redis:
  # redis服务器地址（默认为localhost）
  host: localhost
  # redis端口（默认为6379）
  port: 6379
  # redis连接池配置
  pool:
    # 最大可用连接数（默认为8，负数表示无限）
    max-active: -1
    # 最大空闲连接数（默认为8，负数表示无限）
    max-idle: -1
    # 最小空闲连接数（默认为0，该值只有为正数才有用）
    min-idle: 0
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
    max-wait: -1

tencent:
  cos:
    secret-id: AKIDFOWaYXM5pPr9KPUQFwWo07A62ySuaggV
    secret-key: mQuXzHSK3awJamstwseHk2BFAtT9jHlL
    bucket: savememory-1320078852









